package Modules

var TrnCodMap = map[string]string{
	BOCB2E_OPTS_HOSPITAL_PAYMENT:                   "b2e0009",
	BOCB2E_OPTS_COMPANY_FACTORING:                  "b2e0477",
	BOCB2E_OPTS_COMPANY_FACTORING_REPAYMENT:        "b2e0481",
	BOCB2E_OPTS_COMPANY_FACTORING_REPAYMENT_NOTICE: "b2e0486",
	BOCB2E_OPTS_COMPANY_FACTORING_REPAYMENT_RESULT: "b2e0487",
	BOCB2E_OPTS_ACCOUNT_TRANSACTIONS_QUERY:         "b2e0035",
	BOCB2E_OPTS_HOSPITAL_ACCOUNT_BALANCE:           "b2e0005",
	BOCB2E_OPTS_INVOICE_SUBMIT:                     "b2e0080",
	BOCB2E_OPTS_PAYMENT_REQUEST:                    "b2e0081",
	BOCB2E_OPTS_RAISE_REQUEST:                      "b2e0057",
	BOCB2E_OPTS_PAYMENTS_QUERY:                     "b2e0007",
	BOCB2E_OPTS_TRANSFER_LIMIT_QUERY:               "b2e0058",
	BOCB2E_OPTS_FACTORING_RESULT:                   "b2e0483",
	BOCB2E_OPTS_FILL_UP:                            "b2e0232",
	BOCB2E_OPTS_RECEIPT_DOWNLOAD:                   "b2e0500",
	BOCB2E_OPTS_BALANCE_STATEMENT_QUERY:            "b2e0358",
	BOCB2E_OPTS_BALANCE_STATEMENT_DOWNLOAD:         "b2e0359",
	BOCB2E_OPTS_BALANCE_STATEMENT_FEEDBACK:         "b2e0360",
	BOCB2E_OPTS_CNAPS_QUERY:                        "b2e0043",
}
